# Generated by Django 3.2 on 2023-05-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id_tipo_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_propiedad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('dia_visita', models.TimeField()),
                ('hora_visita', models.DateField()),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('valor_propiedad', models.IntegerField()),
                ('arriendo_propiedad', models.IntegerField()),
                ('venta_propiedad', models.IntegerField()),
                ('id_tipo_propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipopropiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=30)),
                ('id_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicasPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitorios_propiedad', models.IntegerField()),
                ('banos_propiedad', models.IntegerField()),
                ('mascotas_propiedad', models.IntegerField()),
                ('bodega_propiedad', models.IntegerField()),
                ('estacionamiento', models.IntegerField()),
                ('id_propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.propiedad')),
            ],
        ),
    ]
