# Generated by Django 3.2 on 2023-05-17 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='arriendo_propiedad',
            new_name='es_arriendo',
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='venta_propiedad',
            new_name='es_venta',
        ),
        migrations.AlterField(
            model_name='caracteristicaspropiedad',
            name='id_propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.propiedad', unique=True),
        ),
    ]
