# Generated by Django 4.1.7 on 2023-07-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='observacion_denegacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
