# Generated by Django 3.2 on 2023-05-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230516_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristicaspropiedad',
            old_name='banos_propiedad',
            new_name='cant_banos',
        ),
        migrations.RenameField(
            model_name='caracteristicaspropiedad',
            old_name='bodega_propiedad',
            new_name='cant_dormitorios',
        ),
        migrations.RenameField(
            model_name='caracteristicaspropiedad',
            old_name='dormitorios_propiedad',
            new_name='permite_mascotas',
        ),
        migrations.RenameField(
            model_name='caracteristicaspropiedad',
            old_name='estacionamiento',
            new_name='tiene_bodega',
        ),
        migrations.RenameField(
            model_name='caracteristicaspropiedad',
            old_name='mascotas_propiedad',
            new_name='tiene_estacionamiento',
        ),
    ]
