# Generated by Django 3.2 on 2023-05-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230516_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='dia_visita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visita',
            name='hora_visita',
            field=models.TimeField(),
        ),
    ]
