# Generated by Django 4.1.7 on 2023-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230516_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='capital_region',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre_region',
            field=models.CharField(max_length=70),
        ),
    ]
