# Generated by Django 4.1.7 on 2023-05-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_propiedad_id_comuna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristicaspropiedad',
            options={'ordering': ['id_propiedad']},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['id_comuna']},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'ordering': ['id_propiedad']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['id_region']},
        ),
        migrations.AlterModelOptions(
            name='tipopropiedad',
            options={'ordering': ['id_tipo_propiedad']},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['id_visita']},
        ),
    ]
