# Generated by Django 3.2 on 2023-05-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_caracteristicaspropiedad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicaspropiedad',
            name='metros_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caracteristicaspropiedad',
            name='metros_utiles',
            field=models.IntegerField(default=0),
        ),
    ]
