# Generated by Django 4.1.7 on 2023-05-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20230519_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicaspropiedad',
            name='id_propiedad',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.propiedad'),
        ),
    ]
