# Generated by Django 4.1.7 on 2023-06-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_caracteristicaspropiedad_id_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPropiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_propiedad', models.IntegerField()),
                ('valor_propiedad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_arriendo', models.BooleanField()),
                ('es_venta', models.BooleanField()),
                ('nombre_tipo_propiedad', models.CharField(max_length=255)),
                ('nombre_comuna', models.CharField(max_length=255)),
                ('nombre_region', models.CharField(max_length=255)),
                ('capital_region', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'VISTA_DETALLE_PROPIEDAD',
                'managed': False,
            },
        ),
    ]
