# Generated by Django 4.1.7 on 2023-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_usuario_cambios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('id_pruebas', models.AutoField(primary_key=True, serialize=False)),
                ('prueba_bool', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cambios',
        ),
    ]
