# Generated by Django 4.1.7 on 2023-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_pruebas_remove_usuario_cambios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pruebas',
        ),
    ]
