# Generated by Django 4.1.7 on 2023-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_delete_pruebas'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='esta_habilitado',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='es_arriendo',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='es_venta',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
