# Generated by Django 4.1.7 on 2023-06-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_propiedad_esta_habilitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='esta_habilitado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_superusuario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='esta_habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
