# Generated by Django 4.1.7 on 2023-06-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_propiedad_esta_habilitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicaspropiedad',
            name='permite_mascotas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='caracteristicaspropiedad',
            name='tiene_bodega',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='caracteristicaspropiedad',
            name='tiene_estacionamiento',
            field=models.BooleanField(default=True),
        ),
    ]
