# Generated by Django 4.1.7 on 2023-06-19 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0020_alter_caracteristicaspropiedad_permite_mascotas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'MAESTRO_PERFILES',
                'ordering': ['id_perfil'],
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id_usuario']},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_superusuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='esta_habilitado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='region',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='auth_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='caracteristicaspropiedad',
            name='id_propiedad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.propiedad'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.region'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.comuna'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id_tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tipopropiedad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='MAESTRO_USUARIOS',
        ),
        migrations.CreateModel(
            name='PerfilesUsuario',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.perfiles')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.usuario')),
            ],
            options={
                'db_table': 'MAESTRO_ASOC_USUARIO_PERFILES',
                'ordering': ['id_usuario', 'id_perfil'],
            },
        ),
    ]
